trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--filter Category!=End-to-end'
  env:
    COSMOS_DB_CONN_STRING: $(COSMOS_DB_CONN_STRING)
    COSMOS_DB_NAME: $(COSMOS_DB_NAME)
