steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: 'Category!=End-to-end'
    testRunTitle: 'All but end-to-end tests'
