// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Squip.EntityFramework;

namespace Squip.EntityFramework.Migrations
{
    [DbContext(typeof(SquipContext))]
    partial class SquipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Squip.Pocos.SquipPoco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DeletedAt");

                    b.Property<bool>("IsSoftDeleted");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("squips");
                });

            modelBuilder.Entity("Squip.Pocos.TagPoco", b =>
                {
                    b.Property<long>("SquipId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DeletedAt");

                    b.Property<bool>("IsSoftDeleted");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("SquipId", "Name");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Squip.Pocos.TagPoco", b =>
                {
                    b.HasOne("Squip.Pocos.SquipPoco", "SquipPoco")
                        .WithMany("TagPocos")
                        .HasForeignKey("SquipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
