// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Squip.Rest.Infrastructure.EntityFramework;

#nullable disable

namespace Squip.Rest.Migrations
{
    [DbContext(typeof(SquipContext))]
    [Migration("20230801053009_HabitTotalPercentileFunctions")]
    partial class HabitTotalPercentileFunctions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Squip.Rest.Habits.Domain.DailyHabitSummary", b =>
                {
                    b.Property<double>("Goal")
                        .HasColumnType("double precision")
                        .HasColumnName("goal");

                    b.ToTable("daily_habit_summaries", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Habits.Domain.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_habits_user_id");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Habits.Domain.Hibit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_occurred_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hibits");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_hibits_habit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hibits_user_id");

                    b.ToTable("hibits", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<Guid?>("LeftId")
                        .HasColumnType("uuid")
                        .HasColumnName("left_id");

                    b.Property<Guid?>("LoserId")
                        .HasColumnType("uuid")
                        .HasColumnName("loser_id");

                    b.Property<Guid?>("RightId")
                        .HasColumnType("uuid")
                        .HasColumnName("right_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("LeftId")
                        .HasDatabaseName("ix_games_left_id");

                    b.HasIndex("LoserId")
                        .HasDatabaseName("ix_games_loser_id");

                    b.HasIndex("RightId")
                        .HasDatabaseName("ix_games_right_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_games_user_id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_games_winner_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<double>("EloRating")
                        .HasColumnType("double precision")
                        .HasColumnName("elo_rating");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ideas");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ideas_user_id");

                    b.ToTable("ideas", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid")
                        .HasColumnName("idea_id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("IdeaId")
                        .HasDatabaseName("ix_tags_idea_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tags_user_id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Logs.Domain.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logs_user_id");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Moods.Domain.Mood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_moods");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_moods_user_id");

                    b.ToTable("moods", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Moods.Domain.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_occurred_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<int>("Magnitude")
                        .HasColumnType("integer")
                        .HasColumnName("magnitude");

                    b.Property<Guid>("MoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("mood_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mood_entries");

                    b.HasIndex("MoodId")
                        .HasDatabaseName("ix_mood_entries_mood_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mood_entries_user_id");

                    b.ToTable("mood_entries", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Targets.Domain.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_targets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_targets_user_id");

                    b.ToTable("targets", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Targets.Domain.TargetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DidEngage")
                        .HasColumnType("boolean")
                        .HasColumnName("did_engage");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_occurred_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<int>("Magnitude")
                        .HasColumnType("integer")
                        .HasColumnName("magnitude");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_target_entries");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_target_entries_target_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_target_entries_user_id");

                    b.ToTable("target_entries", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_created_at");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant_updated_at");

                    b.Property<string>("OidcSub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oidc_sub");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("OidcSub")
                        .HasName("ak_users_oidc_sub");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Squip.Rest.Habits.Domain.Habit", b =>
                {
                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habits_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Habits.Domain.Hibit", b =>
                {
                    b.HasOne("Squip.Rest.Habits.Domain.Habit", "Habit")
                        .WithMany("Hibits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hibits_habits_habit_id");

                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hibits_users_user_id");

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Game", b =>
                {
                    b.HasOne("Squip.Rest.Ideas.Domain.Idea", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .HasConstraintName("fk_games_ideas_left_id");

                    b.HasOne("Squip.Rest.Ideas.Domain.Idea", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId")
                        .HasConstraintName("fk_games_ideas_loser_id");

                    b.HasOne("Squip.Rest.Ideas.Domain.Idea", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .HasConstraintName("fk_games_ideas_right_id");

                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_users_user_id");

                    b.HasOne("Squip.Rest.Ideas.Domain.Idea", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("fk_games_ideas_winner_id");

                    b.Navigation("Left");

                    b.Navigation("Loser");

                    b.Navigation("Right");

                    b.Navigation("User");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Idea", b =>
                {
                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ideas_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Tag", b =>
                {
                    b.HasOne("Squip.Rest.Ideas.Domain.Idea", "Idea")
                        .WithMany("Tags")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_ideas_idea_id");

                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_users_user_id");

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Logs.Domain.Log", b =>
                {
                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Moods.Domain.Mood", b =>
                {
                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moods_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Moods.Domain.MoodEntry", b =>
                {
                    b.HasOne("Squip.Rest.Moods.Domain.Mood", "Mood")
                        .WithMany("MoodEntries")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mood_entries_moods_mood_id");

                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mood_entries_users_user_id");

                    b.Navigation("Mood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Targets.Domain.Target", b =>
                {
                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_targets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Targets.Domain.TargetEntry", b =>
                {
                    b.HasOne("Squip.Rest.Targets.Domain.Target", "Target")
                        .WithMany("TargetEntries")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_entries_targets_target_id");

                    b.HasOne("Squip.Rest.Users.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_entries_users_user_id");

                    b.Navigation("Target");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Habits.Domain.Habit", b =>
                {
                    b.Navigation("Hibits");
                });

            modelBuilder.Entity("Squip.Rest.Ideas.Domain.Idea", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Squip.Rest.Moods.Domain.Mood", b =>
                {
                    b.Navigation("MoodEntries");
                });

            modelBuilder.Entity("Squip.Rest.Targets.Domain.Target", b =>
                {
                    b.Navigation("TargetEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
