// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squip.Rest.Repositories;

#nullable disable

namespace Squip.Rest.Migrations
{
    [DbContext(typeof(SquipContext))]
    [Migration("20220612031851_AddTitle")]
    partial class AddTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Squip.Rest.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InstantCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InstantUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LeftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeftId");

                    b.HasIndex("LoserId");

                    b.HasIndex("RightId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InstantCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InstantUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InstantCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InstantUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdeaId", "Name");

                    b.HasIndex("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Game", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Idea", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId");

                    b.HasOne("Squip.Rest.Domain.Idea", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId");

                    b.HasOne("Squip.Rest.Domain.Idea", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.HasOne("Squip.Rest.Domain.Idea", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Left");

                    b.Navigation("Loser");

                    b.Navigation("Right");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Tag", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Idea", "Idea")
                        .WithMany("Tags")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Idea", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
