// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Squip.Rest.Repositories;

#nullable disable

namespace Squip.Rest.Migrations
{
    [DbContext(typeof(SquipContext))]
    [Migration("20230223104130_AddTargets")]
    partial class AddTargets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Squip.Rest.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeftId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RightId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeftId");

                    b.HasIndex("LoserId");

                    b.HasIndex("RightId");

                    b.HasIndex("UserId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Hibit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId");

                    b.ToTable("Hibits");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<double>("EloRating")
                        .HasColumnType("double precision");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Mood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("Squip.Rest.Domain.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Magnitude")
                        .HasColumnType("integer");

                    b.Property<Guid>("MoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MoodId");

                    b.HasIndex("UserId");

                    b.ToTable("MoodEntries");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdeaId", "Name");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Squip.Rest.Domain.TargetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DidEngage")
                        .HasColumnType("boolean");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Magnitude")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("UserId");

                    b.ToTable("TargetEntries");
                });

            modelBuilder.Entity("Squip.Rest.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("InstantCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("InstantUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OidcSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("OidcSub");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Game", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Idea", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId");

                    b.HasOne("Squip.Rest.Domain.Idea", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId");

                    b.HasOne("Squip.Rest.Domain.Idea", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squip.Rest.Domain.Idea", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Left");

                    b.Navigation("Loser");

                    b.Navigation("Right");

                    b.Navigation("User");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Habit", b =>
                {
                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Hibit", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Habit", "Habit")
                        .WithMany("Hibits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Idea", b =>
                {
                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Log", b =>
                {
                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Mood", b =>
                {
                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.MoodEntry", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Mood", "Mood")
                        .WithMany("MoodEntries")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Tag", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Idea", "Idea")
                        .WithMany("Tags")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Target", b =>
                {
                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.TargetEntry", b =>
                {
                    b.HasOne("Squip.Rest.Domain.Target", "Target")
                        .WithMany("TargetEntries")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squip.Rest.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Habit", b =>
                {
                    b.Navigation("Hibits");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Idea", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Mood", b =>
                {
                    b.Navigation("MoodEntries");
                });

            modelBuilder.Entity("Squip.Rest.Domain.Target", b =>
                {
                    b.Navigation("TargetEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
