// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquipApi.EntityFramework;

namespace SquipApi.EntityFramework.Migrations
{
    [DbContext(typeof(SquipContext))]
    [Migration("20180726111621_UseUsersEverywhere")]
    partial class UseUsersEverywhere
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SquipApi.Pocos.Squip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<long>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<long>("ModifiedByUserId");

                    b.Property<DateTime>("ModifiedDateTime");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Squip");
                });

            modelBuilder.Entity("SquipApi.Pocos.SquipTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<long>("ModifiedByUserId");

                    b.Property<DateTime>("ModifiedDateTime");

                    b.Property<long>("SquipId");

                    b.Property<long>("TagId");

                    b.HasKey("Id");

                    b.HasAlternateKey("TagId", "SquipId");

                    b.HasIndex("SquipId");

                    b.ToTable("SquipTag");
                });

            modelBuilder.Entity("SquipApi.Pocos.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<long>("ModifiedByUserId");

                    b.Property<DateTime>("ModifiedDateTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("SquipApi.Pocos.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Picture");

                    b.Property<string>("ThirdPartyId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("ThirdPartyId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SquipApi.Pocos.SquipTag", b =>
                {
                    b.HasOne("SquipApi.Pocos.Squip", "Squip")
                        .WithMany("SquipTags")
                        .HasForeignKey("SquipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SquipApi.Pocos.Tag", "Tag")
                        .WithMany("SquipTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
