// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquipApi.WebApi.Models;

namespace SquipApi.WebApi.Migrations
{
    [DbContext(typeof(SquipContext))]
    [Migration("20180723064358_JoinWithTags")]
    partial class JoinWithTags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SquipApi.WebApi.Models.Squip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Squips");
                });

            modelBuilder.Entity("SquipApi.WebApi.Models.SquipTag", b =>
                {
                    b.Property<string>("TagName");

                    b.Property<long>("SquipId");

                    b.HasKey("TagName", "SquipId");

                    b.HasIndex("SquipId");

                    b.ToTable("SquipTag");
                });

            modelBuilder.Entity("SquipApi.WebApi.Models.Tag", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SquipApi.WebApi.Models.SquipTag", b =>
                {
                    b.HasOne("SquipApi.WebApi.Models.Squip", "Squip")
                        .WithMany("SquipTags")
                        .HasForeignKey("SquipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SquipApi.WebApi.Models.Tag", "Tag")
                        .WithMany("SquipTags")
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
